@echo off
rem ============================================================================
rem  gen_version.bat
rem    Keil BeforeMake pre-build script: write BSP/bsp_version.c with version info
rem    - base version : read from VERSION file (manually maintained)
rem    - git hash/tag/date : from git (fallback to placeholders if no git)
rem    - build time  : powershell ISO format (fallback to commit date)
rem    Always produces a valid bsp_version.c regardless of git/powershell.
rem    NOTE: keep this file ASCII-only (cmd.exe parses bat in OEM codepage).
rem    NOTE: git %ci is read via temp file (for /f in('...') re-parses % in subshell).
rem ============================================================================
setlocal
chcp 65001 >nul

set "ROOT=%~dp0.."
set "VERSION_FILE=%ROOT%\VERSION"
set "OUT=%ROOT%\BSP\bsp_version.c"
set "TF=%TEMP%\_genversion.txt"

rem ---- 1. base version (default 1.0.0) ----
set "VER=1.0.0"
if exist "%VERSION_FILE%" set /p VER=<"%VERSION_FILE%"

rem ---- 2. git hash (short) ----
set "HASH=0000000"
git -C "%ROOT%" rev-parse --short HEAD > "%TF%" 2>nul
if exist "%TF%" set /p HASH=<"%TF%"

rem ---- 3. git describe (tag or hash) ----
set "TAG=%VER%"
git -C "%ROOT%" describe --tags --always > "%TF%" 2>nul
if exist "%TF%" set /p TAG=<"%TF%"

rem ---- 4. git commit date (ISO, e.g. 2026-09-14 20:25:21 +0800) ----
set "CDATE=unknown"
git -C "%ROOT%" show -s "--format=%%ci" HEAD > "%TF%" 2>nul
if exist "%TF%" set /p CDATE=<"%TF%"
if exist "%TF%" del "%TF%"

rem ---- 5. build time (powershell ISO; fallback to commit date) ----
set "BTIME=%CDATE%"
for /f "delims=" %%i in ('powershell -NoProfile -Command "(Get-Date).ToString('yyyy-MM-dd HH:mm:ss')" 2^>nul') do set "BTIME=%%i"

rem ---- 6. write bsp_version.c line by line ----
> "%OUT%" echo /******************************************************************************
>>"%OUT%" echo  * bsp_version.c  -  AUTO-GENERATED by Scripts/gen_version.bat. DO NOT EDIT.
>>"%OUT%" echo  * ver=%VER% hash=%HASH% tag=%TAG% date=%CDATE% build=%BTIME%
>>"%OUT%" echo  ******************************************************************************/
>>"%OUT%" echo #include "bsp_version.h"
>>"%OUT%" echo #include ^<stdio.h^>
>>"%OUT%" echo.
>>"%OUT%" echo const char fw_version_string[] = "%VER%";
>>"%OUT%" echo const char fw_git_hash[]       = "%HASH%";
>>"%OUT%" echo const char fw_git_tag[]        = "%TAG%";
>>"%OUT%" echo const char fw_commit_date[]    = "%CDATE%";
>>"%OUT%" echo const char fw_build_time[]     = "%BTIME%";
>>"%OUT%" echo.
>>"%OUT%" echo void bsp_version_print(void)
>>"%OUT%" echo {
>>"%OUT%" echo     printf("[FW] %%s+%%s (%%s) build %%s\n",
>>"%OUT%" echo            fw_version_string, fw_git_hash, fw_commit_date, fw_build_time);
>>"%OUT%" echo }

echo [gen_version] %VER%+%HASH% (%CDATE%) build %BTIME%
exit /b 0
